block_cipher = None

a = Analysis(
    ['comic.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resources', 'resources'),
        ('docs', 'docs'),
    ],
    hiddenimports=[
        'PySide6.QtSvg',
        'PySide6.QtNetwork',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets',
        'onnxruntime',
        'shapely',
        'pyclipper',
        'mahotas',
        'PIL',
        'numpy',
        'msgpack',
        'py7zr',
        'rarfile',
        'pypdfium2',
        'keyring',
        'jaconv',
        'wget',
        'send2trash',
        'PyJWT',
        'PhotoshopAPI',
        'requests',
        'six',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'IPython',
        'notebook',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

exe = EXE(
    PYZ(a.pure, a.zipped_data, cipher=block_cipher),
    a.scripts,
    [],
    a.binaries,
    a.datas,
    [],
    name='comic-translate',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
)

coll = COLLECT(
    exe,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name='comic-translate',
)
