block_cipher = None

a = Analysis(
    ['comic.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resources', 'resources'),
        ('docs', 'docs'),
    ],
    hiddenimports=[
        'PySide6.QtSvg',
        'PySide6.QtNetwork',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets',
        'onnxruntime',
        'shapely',
        'pyclipper',
        'mahotas',
        'PIL',
        'numpy',
        'msgpack',
        'py7zr',
        'rarfile',
        'pypdfium2',
        'keyring',
        'jaconv',
        'wget',
        'send2trash',
        'PyJWT',
        'PhotoshopAPI',
        'requests',
        'six',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'IPython',
        'notebook',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

app = BUNDLE(
    COLLECT(
        EXE(
            PYZ(a.pure, a.zipped_data, cipher=block_cipher),
            a.scripts,
            [],
            a.binaries,
            a.datas,
            [],
            name='Comic Translate',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=False,
            console=False,
            icon='resources/icons/icon.icns',
        ),
        a.zipfiles,
        a.datas,
        [],
        name='Comic Translate',
    ),
    bundle_identifier='com.comiclabs.comictranslate',
    info_plist={
        'CFBundleShortVersionString': __import__('app.version', fromlist=['__version__']).__version__,
        'CFBundleVersion': __import__('app.version', fromlist=['__version__']).__version__,
        'CFBundleName': 'Comic Translate',
        'CFBundleDisplayName': 'Comic Translate',
        'CFBundleIconFile': 'icon.icns',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '12.0',
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': 'Comic Translate Project',
                'CFBundleTypeExtensions': ['ctpr'],
                'CFBundleTypeIconFile': 'file_icon.icns',
                'CFBundleTypeRole': 'Editor',
            }
        ],
    },
)
